---
- hosts: host
  remote_user: root
  gather_facts: no       # For now do not gather facts, but would like to gather
                         # facts and use the disks from gathered facts

  # This will be one-to-one mapping. Every listed disk will have a pv,
  # corresponding vg, and corresponding lv.

  tasks:
  # Create pv on all the disks
  - name: Create Physical Volume on all the nodes
    pv: action=remove disks="{{ bricks }}"
    #with_items: bricks

